### ISSUE TITLE
BadMapError exception when non map value is passed as value for nested schema

### ISSUE THREAD

**Issue by codyburrito** [bluzky/tarams#23]
Reproductions
```ex
schema = %{ test: %{ nested: %{ schema: :string }}}
Tarams.cast(%{ test: %{ nested: []}}, schema)
Tarams.cast(%{ test: %{ nested: 1}}, schema)
Tarams.cast(%{ test: %{ nested: "nested"}}, schema)
```

Expected:
```ex
{:error, %{test: %{nested: ["is invalid"]}}}
```

Actual:
```ex
** (BadMapError) expected a map, got: []
    (stdlib 4.0.1) :maps.find(:schema, [])
    (tarams 1.7.0) lib/tarams.ex:125: Tarams.get_value/3
    (tarams 1.7.0) lib/tarams.ex:107: Tarams.do_cast/3
    (tarams 1.7.0) lib/tarams.ex:83: Tarams.cast_field/2
    (elixir 1.13.4) lib/enum.ex:1597: anonymous fn/3 in Enum.map/2
    (stdlib 4.0.1) maps.erl:411: :maps.fold_1/3
    (elixir 1.13.4) lib/enum.ex:2408: Enum.map/2
    (tarams 1.7.0) lib/tarams.ex:63: Tarams.cast_data/2
    (tarams 1.7.0) lib/tarams.ex:38: Tarams.cast/2
    (tarams 1.7.0) lib/tarams.ex:112: Tarams.do_cast/3
    (tarams 1.7.0) lib/tarams.ex:83: Tarams.cast_field/2
    (elixir 1.13.4) lib/enum.ex:1597: anonymous fn/3 in Enum.map/2
    (stdlib 4.0.1) maps.erl:411: :maps.fold_1/3
    (elixir 1.13.4) lib/enum.ex:2408: Enum.map/2
    (tarams 1.7.0) lib/tarams.ex:63: Tarams.cast_data/2
    (tarams 1.7.0) lib/tarams.ex:38: Tarams.cast/2
    (tarams 1.7.0) lib/tarams.ex:112: Tarams.do_cast/3
    (tarams 1.7.0) lib/tarams.ex:83: Tarams.cast_field/2
    (elixir 1.13.4) lib/enum.ex:1597: anonymous fn/3 in Enum.map/2
    (stdlib 4.0.1) maps.erl:411: :maps.fold_1/3
```

The `get_value` function can probably use a guard for maps and have another function head to return the error.  Might need to include `:ok` and `:error` so we can handle the result before attempting to cast

```ex
defp get_value(data, field_name, default \\ nil) when is_map(data) do
  case Map.fetch(data, field_name) do
    {:ok, value} -> {:ok, value}
    _ ->
      case Map.fetch(data, "#{field_name}") do
        {:ok, value} -> {:ok, value}
        _ -> {:ok, default}
      end
  end
end

defp get_value(data, _field_name, default) when not is_nil(default), do: {:ok, default}
defp get_value(_date, _field_name, _default), do: :error
```

Then we can update the `do_cast` function to account for this new source of errors

```ex
  defp do_cast(data, field_name, definitions) do
    field_name =
      if definitions[:from] do
        definitions[:from]
      else
        field_name
      end

    apply_cast = fn value ->
      case definitions[:cast_func] do
        nil -> cast_value(value, definitions[:type])
        func -> apply_function(func, value, data)
      end
    end

    with {:ok, value} <- get_value(data, field_name, definitions[:default]),
         {:ok, value} <- apply_cast(value) do
      {:ok, value}
    else
      {:error, "is invalid"}
    end
  end

```

I can make this change, just wanted to hear some input or maybe some alternative ways around this issue I did not think of

**Comment by bluzky** [comment]
Thanks @codyburrito,
This actually affects many place, I will do a quick fix. Thank you for your suggestion.

**Comment by bluzky** [comment]
Latest version has been published to hex.pm that fix this issue. Thank you

**Comment by codyburrito** [comment]
Amazing! Thank you!
